USE marketing_campaign_data;

SELECT * FROM campaign_performance;

SELECT p_date,SUM(spend) AS total_spend,SUM(revenue) AS total_revenue,SUM(orders) AS total_orders 
FROM campaign_performance 
GROUP BY p_date;

-- Total spend across all campaigns.
SELECT FORMAT(SUM(spend),0) AS total_spend FROM campaign_performance;

-- Total revenue generated.
SELECT FORMAT(SUM(revenue),0) FROM campaign_performance;

-- Average daily spend.
SELECT p_date,ROUND(AVG(spend),2) AS average_spend 
FROM campaign_performance 
GROUP BY p_date;

-- Campaign that generated the highest revenue.
SELECT p.c_name,FORMAT(SUM(c.revenue),0) AS total_revenue 
FROM campaign_performance c JOIN campaigns p ON p.id=c.campaign_id 
GROUP BY p.c_name 
ORDER BY SUM(revenue) DESC LIMIT 1;

-- Region with the highest spend.
SELECT r.city,r.state,r.zone,SUM(c.spend) AS total_spend 
FROM campaign_performance c JOIN regions r ON r.region_id=c.region_id 
GROUP BY 1,2,3 
ORDER BY total_spend DESC LIMIT 1;

-- Total orders by region.
SELECT r.city,r.state,r.zone,SUM(c.orders) AS total_orders 
FROM campaign_performance c JOIN regions r ON r.region_id=c.region_id 
GROUP BY 1,2,3 
ORDER BY total_orders DESC;

-- Total revenue generated by each campaign.
SELECT p.c_name,FORMAT(SUM(c.revenue),0) AS total_revenue 
FROM campaign_performance c JOIN campaigns p ON p.id=c.campaign_id 
GROUP BY p.c_name 
ORDER BY SUM(revenue) DESC;

-- Highest revenue generating product.
SELECT p.product_name,FORMAT(SUM(c.revenue),0) AS total_revenue 
FROM campaign_performance c JOIN products p ON p.product_id=c.product_id 
GROUP BY p.product_name 
ORDER BY SUM(revenue) DESC LIMIT 1;

-- Channel-wise revenue.
SELECT p.channel_name,FORMAT(SUM(c.revenue),0) AS total_revenue 
FROM campaign_performance c JOIN campaigns d ON c.campaign_id=d.id JOIN channels p ON p.channel_id=d.channel_id
GROUP BY p.channel_name;

-- City with the most orders.
SELECT r.city,r.state,SUM(c.orders) AS total_orders 
FROM campaign_performance c JOIN regions r ON r.region_id=c.region_id 
GROUP BY 1,2
ORDER BY total_orders DESC LIMIT 1;

-- Total spend by product category.
SELECT p.category,FORMAT(SUM(c.spend),0) AS total_spend
FROM campaign_performance c JOIN products p ON p.product_id=c.product_id 
GROUP BY p.category;

-- CTR for each campaign.
-- CTR = (Clicks / Impressions) × 100
SELECT p.c_name,ROUND((SUM(c.clicks)/SUM(c.impressions))*100.0,2) AS ctr
FROM campaign_performance c JOIN campaigns p ON p.id=c.campaign_id 
GROUP BY p.c_name;

-- CPC for every campaign.
-- CPC = Spend / Clicks
SELECT p.c_name,ROUND((SUM(c.spend)/SUM(c.clicks)),2) AS cpc
FROM campaign_performance c JOIN campaigns p ON p.id=c.campaign_id 
GROUP BY p.c_name;

-- CPL.
-- CPL = Spend / Leads
SELECT ROUND((SUM(spend)/SUM(leads)),2) AS cpl
FROM campaign_performance;

-- CPL by channel
SELECT p.channel_name,ROUND((SUM(c.spend)/SUM(c.leads)),2) AS cpl
FROM campaign_performance c JOIN campaigns d ON c.campaign_id=d.id JOIN channels p ON p.channel_id=d.channel_id
GROUP BY p.channel_name;

-- Conversion Rate.
-- Orders / Clicks
SELECT ROUND((SUM(orders)/SUM(clicks))*100.0,2) AS conversion_rate
FROM campaign_performance;

-- ROAS.
-- Revenue / Spend
SELECT ROUND((SUM(revenue)/SUM(spend)),2) AS roas
FROM campaign_performance;

-- Top 5 campaigns by revenue.
SELECT p.c_name,FORMAT(SUM(c.revenue),0) AS total_revenue 
FROM campaign_performance c JOIN campaigns p ON p.id=c.campaign_id 
GROUP BY p.c_name 
ORDER BY SUM(revenue) DESC LIMIT 5;

-- Top 5 cities by revenue.
SELECT r.city,FORMAT(SUM(c.revenue),0) AS total_revenue
FROM campaign_performance c JOIN regions r ON r.region_id=c.region_id 
GROUP BY r.city
ORDER BY SUM(c.revenue) DESC LIMIT 5;

-- Month with the highest revenue.
SELECT MONTHNAME(p_date) AS month_name,FORMAT(SUM(c.revenue),0) AS total_revenue
FROM campaign_performance c
GROUP BY MONTHNAME(p_date)
ORDER BY SUM(c.revenue) DESC LIMIT 1;

-- Device that generated the most revenue.
SELECT device,FORMAT(SUM(c.revenue),0) AS total_revenue,ROUND((SUM(c.clicks)/SUM(c.impressions))*100.0,2) AS ctr,
ROUND((SUM(orders)/SUM(clicks))*100.0,2) AS conversion_rate
FROM campaign_performance c
GROUP BY device
ORDER BY SUM(c.revenue) DESC;

-- Age group that generated the highest revenue.
SELECT age_group,FORMAT(SUM(c.revenue),0) AS total_revenue
FROM campaign_performance c
GROUP BY age_group
ORDER BY SUM(c.revenue) DESC LIMIT 1;

-- Rank campaigns based on revenue.
SELECT p.c_name,FORMAT(SUM(c.revenue),0) AS total_revenue,DENSE_RANK() OVER(ORDER BY SUM(revenue) DESC) AS rnk
FROM campaign_performance c JOIN campaigns p ON p.id=c.campaign_id
GROUP BY p.c_name;

-- Running total of revenue by date.
WITH cte AS(
    SELECT p_date,SUM(revenue) AS daily_revenue
    FROM campaign_performance
    GROUP BY p_date
)
SELECT p_date,daily_revenue,SUM(daily_revenue) OVER (ORDER BY p_date) AS running_total
FROM cte;

-- Previous day's revenue using LAG().
WITH cte AS(
SELECT p_date,SUM(revenue) as daily_revenue
FROM campaign_performance
GROUP BY p_date 
)
SELECT p_date,daily_revenue,LAG(daily_revenue) OVER(ORDER BY p_date) AS prev_day_revenue
FROM cte;

-- Month-over-month revenue growth.
WITH cte AS(
SELECT MONTH(p_date) AS month_no,MONTHNAME(p_date) AS month_name,SUM(revenue) AS month_revenue
FROM campaign_performance
GROUP BY MONTHNAME(p_date),month_no
)
SELECT month_no,month_name,FORMAT(month_revenue,0),FORMAT(LAG(month_revenue) OVER(ORDER BY month_no),0) AS prev_month_revenue,
ROUND(
((month_revenue-(LAG(month_revenue) OVER(ORDER BY month_no)))
/(LAG(month_revenue) OVER(ORDER BY month_no))
)*100
,2) AS MoM_growth
FROM cte;

-- Top-performing campaign within each channel.
WITH cte AS(
SELECT e.channel_name,d.c_name,SUM(c.revenue) AS total_revenue,SUM(c.orders) AS total_orders,
DENSE_RANK() OVER(PARTITION BY e.channel_id ORDER BY SUM(c.revenue) DESC) AS rnk
FROM campaign_performance c JOIN campaigns d ON c.campaign_id=d.id JOIN channels e ON d.channel_id=e.channel_id
GROUP BY c.campaign_id
)
SELECT * FROM cte WHERE rnk=1;

-- Suppose we have 10 lakh budget next month. Which channel should get more investment?
WITH cte AS (
SELECT campaign_id,SUM(revenue) AS total_revenue,
SUM(spend) AS total_spend,SUM(orders) AS total_orders,
ROUND((SUM(revenue)/SUM(spend)),2) AS roas,
ROUND((SUM(orders)/SUM(clicks))*100.0,2) AS conversion_rate
FROM campaign_performance
GROUP BY campaign_id
)
SELECT p.channel_name,
FORMAT(SUM(c.total_spend), 0) AS total_spend,
FORMAT(SUM(c.total_revenue), 0) AS total_revenue,
SUM(c.total_orders) AS total_orders,
ROUND(AVG(c.conversion_rate),2) AS avg_conversion_rate,
ROUND(AVG(c.roas),2) AS avg_roas,
FORMAT(SUM(d.budget),0) AS total_budget
FROM cte c JOIN campaigns d ON c.campaign_id = d.id JOIN channels p ON p.channel_id = d.channel_id
GROUP BY p.channel_name
ORDER BY avg_roas DESC,total_orders DESC,SUM(c.total_revenue) DESC;

-- Campaigns that are spending a lot but generating poor revenue.
SELECT p.c_name,FORMAT(SUM(c.spend),0) AS total_spend,FORMAT(SUM(c.revenue),0) AS total_revenue,
ROUND((SUM(c.revenue)/SUM(c.spend)),2) AS roas
FROM campaign_performance c JOIN campaigns p ON p.id=c.campaign_id
GROUP BY p.c_name
ORDER BY roas;

-- Product to be promoted more next quarter.
SELECT p.product_name,FORMAT(SUM(c.revenue),0) AS total_revenue,ROUND((SUM(c.orders)/SUM(c.clicks))*100.0,2) AS conversion_rate
FROM campaign_performance c JOIN products p ON p.product_id=c.product_id
GROUP BY p.product_name ORDER BY SUM(c.revenue) DESC;

-- Underperforming regions.
SELECT r.city,FORMAT(SUM(c.revenue),0) AS total_revenue,SUM(c.orders),ROUND((SUM(c.revenue)/SUM(c.spend)),2) AS roas,
ROUND((SUM(c.orders)/SUM(c.clicks))*100.0,2) AS conversion_rate
FROM campaign_performance c JOIN regions r ON r.region_id=c.region_id
GROUP BY r.city ORDER BY roas;

-- Customer segment (age+gender+device) that brings the highest revenue.
SELECT age_group,gender,device,FORMAT(SUM(revenue),0) AS total_revenue,SUM(orders),ROUND((SUM(revenue)/SUM(spend)),2) AS roas,
ROUND((SUM(orders)/SUM(clicks))*100.0,2) AS conversion_rate
FROM campaign_performance WHERE gender<>"Unknown"
GROUP BY age_group,gender,device ORDER BY SUM(revenue) DESC;

-- Budget utilization
SELECT p.c_name,FORMAT(p.budget, 0) AS budget,FORMAT(SUM(c.spend), 0) AS actual_spend,FORMAT(p.budget - SUM(c.spend), 0) AS remaining_budget,
ROUND((SUM(c.spend) / p.budget) * 100, 2) AS budget_utilization_pct
FROM campaign_performance c JOIN campaigns p ON p.id = c.campaign_id
GROUP BY p.id, p.c_name, p.budget
ORDER BY budget_utilization_pct DESC;

-- Highest revenue-generating product within each region.
WITH cte AS(
SELECT r.city,p.product_name,FORMAT(SUM(c.revenue),0) AS total_revenue,
RANK() OVER(PARTITION BY r.city ORDER BY SUM(c.revenue) DESC) AS RNK
FROM campaign_performance c JOIN regions r ON r.region_id=c.region_id JOIN products p ON p.product_id=c.product_id
GROUP BY r.city,p.product_name
)
SELECT * from cte WHERE RNK<=3;

-- Best month for each channel.
WITH cte AS(
SELECT p.channel_name,MONTHNAME(p_date) as month_name,FORMAT(SUM(c.revenue),0) AS total_revenue,
RANK() OVER(PARTITION BY p.channel_name ORDER BY SUM(c.revenue) DESC) AS RNK
FROM campaign_performance c JOIN campaigns r ON r.id=c.campaign_id JOIN channels p ON p.channel_id=r.channel_id
GROUP BY p.channel_name,MONTHNAME(p_date)
)
SELECT * from cte WHERE RNK<=3;

-- Executive Dashboard Query
SELECT p.c_name,FORMAT(SUM(c.revenue),0) AS total_revenue,FORMAT(SUM(c.spend),0) AS total_spend,
ROUND((SUM(c.revenue)/SUM(c.spend)),2) AS roas,SUM(c.orders) AS total_orders,ROUND((SUM(c.clicks)/SUM(c.impressions))*100.0,2) AS ctr,
ROUND((SUM(c.orders)/SUM(c.clicks))*100.0,2) AS conversion_rate
FROM campaign_performance c JOIN campaigns p ON p.id=c.campaign_id
GROUP BY p.c_name
ORDER BY SUM(c.revenue) DESC;